/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-01-21 15:22:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <title>JSP Page</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <header class=\"bg-white\">\n");
      out.write("      <nav\n");
      out.write("        class=\"mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8\"\n");
      out.write("        aria-label=\"Global\"\n");
      out.write("      >\n");
      out.write("        <div class=\"flex lg:flex-1\">\n");
      out.write("          <a href=\"/ResortManagement/pages/Home/index.jsp\" class=\"-m-1.5 p-1.5\">\n");
      out.write("            <span class=\"sr-only\">Resort Hub Logo</span>\n");
      out.write("            <img class=\"h-12 w-auto\" src=\"../assets/images/logo.png\" alt=\"\" />\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"flex lg:hidden\">\n");
      out.write("          <button\n");
      out.write("            type=\"button\"\n");
      out.write("            class=\"-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700\"\n");
      out.write("          >\n");
      out.write("            <span class=\"sr-only\">Open main menu</span>\n");
      out.write("            <svg\n");
      out.write("              class=\"h-6 w-6\"\n");
      out.write("              fill=\"none\"\n");
      out.write("              viewBox=\"0 0 24 24\"\n");
      out.write("              stroke-width=\"1.5\"\n");
      out.write("              stroke=\"currentColor\"\n");
      out.write("              aria-hidden=\"true\"\n");
      out.write("            >\n");
      out.write("              <path\n");
      out.write("                stroke-linecap=\"round\"\n");
      out.write("                stroke-linejoin=\"round\"\n");
      out.write("                d=\"M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5\"\n");
      out.write("              />\n");
      out.write("            </svg>\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"hidden lg:flex lg:gap-x-12\">\n");
      out.write("          <a href=\"/ResortHub/Admin/Dashboard/ListEmployee.jsp\" class=\"text-sm font-semibold leading-6 text-gray-900\"\n");
      out.write("            >Management</a\n");
      out.write("          >\n");
      out.write("          <a href=\"#\" class=\"text-sm font-semibold leading-6 text-gray-900\"\n");
      out.write("            >Features</a\n");
      out.write("          >\n");
      out.write("          <a href=\"#\" class=\"text-sm font-semibold leading-6 text-gray-900\"\n");
      out.write("            >Marketplace</a\n");
      out.write("          >\n");
      out.write("          <a href=\"#\" class=\"text-sm font-semibold leading-6 text-gray-900\"\n");
      out.write("            >Company</a\n");
      out.write("          >\n");
      out.write("        </div>\n");
      out.write("        <div class=\"hidden lg:flex lg:flex-1 lg:justify-end\">\n");
      out.write("          <a\n");
      out.write("            href=\"/ResortHub/pages/Auth/login.jsp\"\n");
      out.write("            class=\"text-sm font-semibold leading-6 text-gray-900\"\n");
      out.write("            >Log in <span aria-hidden=\"true\">&rarr;</span></a\n");
      out.write("          >\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("      <!-- Mobile menu, show/hide based on menu open state. -->\n");
      out.write("      <!--            <div class=\"lg:hidden\" role=\"dialog\" aria-modal=\"true\">\n");
      out.write("                 Background backdrop, show/hide based on slide-over state. \n");
      out.write("                <div class=\"fixed inset-0 z-10\"></div>\n");
      out.write("                <div class=\"fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10\">\n");
      out.write("                    <div class=\"flex items-center justify-between\">\n");
      out.write("                        <a href=\"#\" class=\"-m-1.5 p-1.5\">\n");
      out.write("                            <span class=\"sr-only\">Your Company</span>\n");
      out.write("                            <img class=\"h-12 w-auto\" src=\"../assets/images/logo.png\" alt=\"\">\n");
      out.write("                        </a>\n");
      out.write("                        <button type=\"button\" class=\"-m-2.5 rounded-md p-2.5 text-gray-700\">\n");
      out.write("                            <span class=\"sr-only\">Close menu</span>\n");
      out.write("                            <svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" aria-hidden=\"true\">\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M6 18L18 6M6 6l12 12\" />\n");
      out.write("                            </svg>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-6 flow-root\">\n");
      out.write("                        <div class=\"-my-6 divide-y divide-gray-500/10\">\n");
      out.write("                            <div class=\"space-y-2 py-6\">\n");
      out.write("                                <a href=\"#\" class=\"-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50\">Product</a>\n");
      out.write("                                <a href=\"#\" class=\"-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50\">Features</a>\n");
      out.write("                                <a href=\"#\" class=\"-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50\">Marketplace</a>\n");
      out.write("                                <a href=\"#\" class=\"-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50\">Company</a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"py-6\">\n");
      out.write("                                <a href=\"#\" class=\"-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50\">Log in</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>-->\n");
      out.write("    </header>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
