/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-01-21 15:22:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.Home;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Category_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"bg-white\">\n");
      out.write("            <div class=\"py-16 sm:py-24 xl:mx-auto xl:max-w-7xl xl:px-8\">\n");
      out.write("                <div class=\"px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8 xl:px-0\">\n");
      out.write("                    <h2 class=\"text-2xl font-bold tracking-tight text-gray-900\">International escapes </h2>\n");
      out.write("                    <a href=\"#\" class=\"hidden text-sm font-semibold text-indigo-600 hover:text-indigo-500 sm:block\">\n");
      out.write("                        Get the guides\n");
      out.write("                        <span aria-hidden=\"true\"> &rarr;</span>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mt-4 flow-root\">\n");
      out.write("                    <div class=\"-my-2\">\n");
      out.write("                        <div class=\"relative box-content h-80 overflow-x-auto py-2 \">\n");
      out.write("                            <div class=\"absolute flex space-x-4 px-4 sm:px-6 lg:px-8 xl:relative xl:grid xl:grid-cols-5 xl:gap-x-4 xl:space-x-0 xl:px-0\">\n");
      out.write("                                <a href=\"#\" class=\"relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto\">\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-0\">\n");
      out.write("                                        <img src=\"https://ik.imagekit.io/tvlk/image/imageResource/2023/06/15/1686809670686-39d479a1982b653cabfec3031a1a6b1d.png?tr=q-75,w-256\" \n");
      out.write("                                             alt=\"\" \n");
      out.write("                                             class=\"h-full w-full object-cover object-center\">\n");
      out.write("                                    </span>\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50\"></span>\n");
      out.write("                                    <span class=\"relative mt-auto text-center text-xl font-bold text-white\">Bali</span>\n");
      out.write("                                </a>\n");
      out.write("                                <a href=\"#\" class=\"relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto\">\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-0\">\n");
      out.write("                                        <img src=\"https://ik.imagekit.io/tvlk/image/imageResource/2023/06/15/1686809673729-a58c108356a01e5a0407277df2586bae.png?tr=q-75,w-256\" \n");
      out.write("                                             alt=\"\" \n");
      out.write("                                             class=\"h-full w-full object-cover object-center\">\n");
      out.write("                                    </span>\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50\"></span>\n");
      out.write("                                    <span class=\"relative mt-auto text-center text-xl font-bold text-white\">Bangkok</span>\n");
      out.write("                                </a>\n");
      out.write("                                <a href=\"#\" class=\"relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto\">\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-0\">\n");
      out.write("                                        <img src=\"https://ik.imagekit.io/tvlk/image/imageResource/2023/06/15/1686809678054-620c707b1fe8951b7810fcdff7409dc4.png?tr=q-75,w-256\" alt=\"\" class=\"h-full w-full object-cover object-center\">\n");
      out.write("                                    </span>\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50\"></span>\n");
      out.write("                                    <span class=\"relative mt-auto text-center text-xl font-bold text-white\">Seoul</span>\n");
      out.write("                                </a>\n");
      out.write("                                <a href=\"#\" class=\"relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto\">\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-0\">\n");
      out.write("                                        <img src=\"https://ik.imagekit.io/tvlk/image/imageResource/2023/06/15/1686809681490-91ea692e8ba8d462f997a6e9043e9de3.png?tr=q-75,w-256\" alt=\"\" \n");
      out.write("                                             class=\"h-full w-full object-cover object-center\">\n");
      out.write("                                    </span>\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50\"></span>\n");
      out.write("                                    <span class=\"relative mt-auto text-center text-xl font-bold text-white\">Istanbul</span>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                <a href=\"#\" class=\"relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto\">\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-0\">\n");
      out.write("                                        <img src=\"https://ik.imagekit.io/tvlk/image/imageResource/2023/06/15/1686809684715-b1d790b3eaaf43e4a13fcc14e926f5ba.png?tr=q-75,w-256\" alt=\"\" class=\"h-full w-full object-cover object-center\">\n");
      out.write("                                    </span>\n");
      out.write("                                    <span aria-hidden=\"true\" class=\"absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50\"></span>\n");
      out.write("                                    <span class=\"relative mt-auto text-center text-xl font-bold text-white\">Liverpool</span>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mt-6 px-4 sm:hidden\">\n");
      out.write("                    <a href=\"#\" class=\"block text-sm font-semibold text-indigo-600 hover:text-indigo-500\">\n");
      out.write("                        Browse all categories\n");
      out.write("                        <span aria-hidden=\"true\"> &rarr;</span>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"bg-white\">\n");
      out.write("            <div class=\"mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl\">\n");
      out.write("                <div class=\"relative overflow-hidden rounded-lg lg:h-96\">\n");
      out.write("                    <div class=\"absolute inset-0\">\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1704616950334-38157594e3c9?q=80&w=2370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D\" alt=\"\" class=\"h-full w-full object-cover object-center\">\n");
      out.write("                    </div>\n");
      out.write("                    <div aria-hidden=\"true\" class=\"relative h-96 w-full lg:hidden\"></div>\n");
      out.write("                    <div aria-hidden=\"true\" class=\"relative h-32 w-full lg:hidden\"></div>\n");
      out.write("                    <div class=\"absolute inset-x-0 bottom-0 rounded-bl-lg rounded-br-lg bg-black bg-opacity-75 p-6 backdrop-blur backdrop-filter sm:flex sm:items-center sm:justify-between lg:inset-x-auto lg:inset-y-0 lg:w-96 lg:flex-col lg:items-start lg:rounded-br-none lg:rounded-tl-lg\">\n");
      out.write("                        <div>\n");
      out.write("                            <h2 class=\"text-xl font-bold text-white\">Workspace Collection</h2>\n");
      out.write("                            <p class=\"mt-1 text-sm text-gray-300\">Upgrade your desk with objects that keep you organized and clear-minded.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <a href=\"#\" class=\"mt-6 flex flex-shrink-0 items-center justify-center rounded-md border border-white border-opacity-25 bg-white bg-opacity-0 px-4 py-3 text-base font-medium text-white hover:bg-opacity-10 sm:ml-8 sm:mt-0 lg:ml-0 lg:w-full\">View the collection</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
