/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-01-21 15:22:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.Home;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class HeroSection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("          <div class=\"relative overflow-hidden bg-white\">\n");
      out.write("            <div class=\"hidden lg:absolute lg:inset-0 lg:block\" aria-hidden=\"true\">\n");
      out.write("                <svg class=\"absolute left-1/2 top-0 -translate-y-8 translate-x-64 transform\" width=\"640\" height=\"784\" fill=\"none\" viewBox=\"0 0 640 784\">\n");
      out.write("                <defs>\n");
      out.write("                <pattern id=\"9ebea6f4-a1f5-4d96-8c4e-4c2abf658047\" x=\"118\" y=\"0\" width=\"20\" height=\"20\" patternUnits=\"userSpaceOnUse\">\n");
      out.write("                    <rect x=\"0\" y=\"0\" width=\"4\" height=\"4\" class=\"text-gray-200\" fill=\"currentColor\" />\n");
      out.write("                </pattern>\n");
      out.write("                </defs>\n");
      out.write("                <rect y=\"72\" width=\"640\" height=\"640\" class=\"text-gray-50\" fill=\"currentColor\" />\n");
      out.write("                <rect x=\"118\" width=\"404\" height=\"784\" fill=\"url(#9ebea6f4-a1f5-4d96-8c4e-4c2abf658047)\" />\n");
      out.write("                </svg>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"relative pb-16 pt-6 sm:pb-24 lg:pb-32\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <main class=\"mx-auto mt-16 max-w-7xl px-4 px-6 sm:mt-24 lg:mt-32\">\n");
      out.write("                    <div class=\"lg:grid lg:grid-cols-12 lg:gap-8\">\n");
      out.write("                        <div class=\"sm:text-center md:mx-auto md:max-w-2xl lg:col-span-6 lg:text-left\">\n");
      out.write("                            <h1>\n");
      out.write("                                <span class=\"block text-base font-semibold text-gray-500 sm:text-lg lg:text-base xl:text-lg\">Coming soon</span>\n");
      out.write("                                <span class=\"mt-1 block text-4xl font-bold tracking-tight sm:text-5xl xl:text-6xl\">\n");
      out.write("                                    <span class=\"block text-gray-900\">Streamlining Your</span>\n");
      out.write("                                    <span class=\"block text-indigo-600\">Resort Experience</span>\n");
      out.write("                                </span>\n");
      out.write("                            </h1>\n");
      out.write("                            <p class=\"mt-3 text-base text-gray-500 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl\">ResortHub is an all-in-one resort management website designed to enhance the efficiency and overall experience for both resort owners and guests. </p>\n");
      out.write("                            <div class=\"mt-8 sm:mx-auto sm:max-w-lg sm:text-center lg:mx-0 lg:text-left\">\n");
      out.write("                                <p class=\"text-base font-medium text-gray-900\">Sign up to get notified when it’s ready.</p>\n");
      out.write("                                <form action=\"#\" method=\"POST\" class=\"mt-3 sm:flex\">\n");
      out.write("                                    <label for=\"email\" class=\"sr-only\">Email</label>\n");
      out.write("                                    <input type=\"email\" name=\"email\" id=\"email\" class=\"block w-full rounded-md border-gray-300 py-3 text-base placeholder-gray-500 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:flex-1\" placeholder=\"Enter your email\">\n");
      out.write("                                    <button type=\"submit\" class=\"mt-3 w-full rounded-md border border-transparent bg-gray-800 px-6 py-3 text-base font-medium text-white shadow-sm hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:ml-3 sm:mt-0 sm:inline-flex sm:w-auto sm:flex-shrink-0 sm:items-center\">Notify me</button>\n");
      out.write("                                </form>\n");
      out.write("                                <p class=\"mt-3 text-sm text-gray-500\">\n");
      out.write("                                    We care about the protection of your data. Read our\n");
      out.write("                                    <a href=\"#\" class=\"font-medium text-gray-900 underline\">Privacy Policy</a>.\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"relative mt-12 sm:mx-auto sm:max-w-lg lg:col-span-6 lg:mx-0 lg:mt-0 lg:flex lg:max-w-none lg:items-center\">\n");
      out.write("                            <svg class=\"absolute left-1/2 top-0 origin-top -translate-x-1/2 -translate-y-8 scale-75 transform sm:scale-100 lg:hidden\" width=\"640\" height=\"784\" fill=\"none\" viewBox=\"0 0 640 784\" aria-hidden=\"true\">\n");
      out.write("                            <defs>\n");
      out.write("                            <pattern id=\"4f4f415c-a0e9-44c2-9601-6ded5a34a13e\" x=\"118\" y=\"0\" width=\"20\" height=\"20\" patternUnits=\"userSpaceOnUse\">\n");
      out.write("                                <rect x=\"0\" y=\"0\" width=\"4\" height=\"4\" class=\"text-gray-200\" fill=\"currentColor\" />\n");
      out.write("                            </pattern>\n");
      out.write("                            </defs>\n");
      out.write("                            <rect y=\"72\" width=\"640\" height=\"640\" class=\"text-gray-50\" fill=\"currentColor\" />\n");
      out.write("                            <rect x=\"118\" width=\"404\" height=\"784\" fill=\"url(#4f4f415c-a0e9-44c2-9601-6ded5a34a13e)\" />\n");
      out.write("                            </svg>\n");
      out.write("                            <div class=\"relative mx-auto w-full rounded-lg shadow-lg lg:max-w-md\">\n");
      out.write("                                <button type=\"button\" class=\"relative block w-full overflow-hidden rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2\">\n");
      out.write("                                    <span class=\"sr-only\">Watch our video to learn more</span>\n");
      out.write("                                    <img class=\"w-full\" src=\"https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D\" alt=\"\">\n");
      out.write("                                   \n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </main>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
